"""
Agent 4: Resolution Agent
Responsibility:
  - Generate step-by-step resolution instructions
  - Generate OS-specific PowerShell / CMD scripts
  - Draft resolution summary for IT engineer

Input:  ticket data, root cause analysis, sop_context
Output: {"resolution_steps": list, "script": str, "script_type": str, "summary": str}
"""
import json
import re
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
from config.settings import GROQ_API_KEY, GROQ_MODEL


def _build_llm() -> ChatGroq:
    import os
    key = os.getenv("GROQ_API_KEY") or GROQ_API_KEY
    return ChatGroq(
        api_key=key,
        model=GROQ_MODEL,
        temperature=0.2,
        max_tokens=2048,
    )


RESOLUTION_SYSTEM_PROMPT = """You are a senior Windows IT engineer. Given a support 
ticket's root cause analysis and relevant documentation, provide:
1. Step-by-step resolution instructions for the IT engineer
2. A Windows PowerShell script to automate diagnosis/resolution
3. A brief resolution summary

CRITICAL RULES:
- PowerShell script must be safe — NO destructive operations without confirmation
- Include comments in the script explaining each step
- Steps should be numbered and actionable
- Reference the exact documentation sections that apply

Respond ONLY with valid JSON:
{
  "resolution_steps": [
    "Step 1: Check disk usage by opening Task Manager...",
    "Step 2: Run Disk Cleanup...",
    "Step 3: Clear temporary files..."
  ],
  "script": "# PowerShell script\\n# Step 1: Check disk usage\\nGet-Volume\\n...",
  "script_type": "PowerShell",
  "summary": "Brief summary of the resolution approach (2-3 sentences)",
  "estimated_time": "15 minutes",
  "escalation_needed": false
}"""


def generate_resolution(
    category: str,
    issue_summary: str,
    probable_cause: str,
    severity: str,
    sop_context: str,
    conversation_summary: str = "",
) -> dict:
    """
    Generate resolution steps and script for an IT engineer.

    Returns:
        dict with resolution_steps, script, script_type, summary
    """
    llm = _build_llm()

    prompt = f"""Ticket Details:
Category: {category}
Issue: {issue_summary}
Probable Cause: {probable_cause}
Severity: {severity}

Conversation Summary:
{conversation_summary or "No additional conversation context."}

Relevant Documentation:
{sop_context[:2000]}

Generate resolution steps and a PowerShell diagnostic/remediation script."""

    messages = [
        SystemMessage(content=RESOLUTION_SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    try:
        response = llm.invoke(messages)
        raw = response.content.strip()
        json_match = re.search(r'\{.*\}', raw, re.DOTALL)
        if json_match:
            result = json.loads(json_match.group())
            return result
    except Exception as e:
        pass

    # Fallback resolution based on category
    return _fallback_resolution(category, probable_cause, severity)


def _fallback_resolution(category: str, probable_cause: str, severity: str = "Medium") -> dict:
    """Provide a structured fallback resolution when LLM fails."""
    # Dynamic local RAG fallback: parse matching SOP document directly
    from rag.retriever import parse_sop_file_locally
    local_res = parse_sop_file_locally(category, probable_cause)
    if local_res:
        steps_formatted = [f"Step {i+1}: {step}" for i, step in enumerate(local_res["self_resolution_steps"])]
        return {
            "resolution_steps": steps_formatted,
            "script": local_res["script"],
            "script_type": "PowerShell",
            "summary": f"Suspected {probable_cause}. Loaded specific diagnostics from SOP file.",
            "estimated_time": "15-20 minutes",
            "escalation_needed": severity in ["High", "Critical"]
        }

    scripts = {
        "Performance": """# ITAssist AI - Windows Performance Diagnostics
# Generated by Resolution Agent

Write-Host "=== Windows Performance Diagnostic Report ===" -ForegroundColor Cyan

# Step 1: Check Disk Usage
Write-Host "`n[1] Disk Space Status:" -ForegroundColor Yellow
Get-Volume | Select-Object DriveLetter, FileSystemLabel, @{N='Size(GB)';E={[math]::Round($_.Size/1GB,2)}}, @{N='Free(GB)';E={[math]::Round($_.SizeRemaining/1GB,2)}}, @{N='Used%';E={[math]::Round(($_.Size-$_.SizeRemaining)/$_.Size*100,1)}}

# Step 2: Check CPU Usage
Write-Host "`n[2] Top CPU Processes:" -ForegroundColor Yellow
Get-Process | Sort-Object CPU -Descending | Select-Object -First 10 Name, CPU, @{N='RAM(MB)';E={[math]::Round($_.WorkingSet/1MB,2)}}

# Step 3: Check RAM Usage  
Write-Host "`n[3] Memory Status:" -ForegroundColor Yellow
$os = Get-CimInstance Win32_OperatingSystem
[PSCustomObject]@{
    'Total RAM (GB)' = [math]::Round($os.TotalVisibleMemorySize/1MB,2)
    'Available RAM (GB)' = [math]::Round($os.FreePhysicalMemory/1MB,2)
    'Used %' = [math]::Round(($os.TotalVisibleMemorySize - $os.FreePhysicalMemory)/$os.TotalVisibleMemorySize*100,1)
}

# Step 4: Clean Temp Files (safe - only temp folder)
Write-Host "`n[4] Cleaning temporary files..." -ForegroundColor Yellow
$cleaned = 0
Get-ChildItem $env:TEMP -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
    try { Remove-Item $_.FullName -Force -ErrorAction Stop; $cleaned++ } catch {}
}
Write-Host "   Removed $cleaned temporary files" -ForegroundColor Green

# Step 5: Disk Health Check
Write-Host "`n[5] Disk Health Status:" -ForegroundColor Yellow
Get-PhysicalDisk | Select-Object FriendlyName, HealthStatus, OperationalStatus

Write-Host "`n=== Diagnostic Complete ===" -ForegroundColor Cyan
Write-Host "Review the above output and escalate if disk health shows 'Unhealthy'" -ForegroundColor White""",

        "VPN / Remote Access": """# ITAssist AI - VPN Diagnostics
# Generated by Resolution Agent

Write-Host "=== VPN Connectivity Diagnostic Report ===" -ForegroundColor Cyan

# Step 1: Check internet connectivity
Write-Host "`n[1] Internet Connectivity:" -ForegroundColor Yellow
$ping = Test-Connection -ComputerName 8.8.8.8 -Count 2 -Quiet
Write-Host "   Internet reachable: $ping"

# Step 2: List VPN connections
Write-Host "`n[2] Configured VPN Connections:" -ForegroundColor Yellow
Get-VpnConnection | Select-Object Name, ConnectionStatus, ServerAddress, TunnelType

# Step 3: Check DNS
Write-Host "`n[3] DNS Resolution Test:" -ForegroundColor Yellow
try { 
    Resolve-DnsName google.com -ErrorAction Stop | Select-Object -First 1
    Write-Host "   DNS working correctly" -ForegroundColor Green
} catch {
    Write-Host "   DNS resolution failed!" -ForegroundColor Red
}

# Step 4: Reset network stack (uncomment to execute)
Write-Host "`n[4] Network Reset Commands (review before running):" -ForegroundColor Yellow
Write-Host "   ipconfig /flushdns"
Write-Host "   ipconfig /release"
Write-Host "   ipconfig /renew"
Write-Host "   netsh winsock reset (requires restart)"

# Step 5: Check Windows Firewall
Write-Host "`n[5] Windows Firewall Status:" -ForegroundColor Yellow
Get-NetFirewallProfile | Select-Object Name, Enabled

Write-Host "`n=== Diagnostic Complete ===" -ForegroundColor Cyan""",

        "Printer": """# ITAssist AI - Printer Diagnostics
# Generated by Resolution Agent

Write-Host "=== Printer Diagnostic Report ===" -ForegroundColor Cyan

# Step 1: List all printers
Write-Host "`n[1] Installed Printers:" -ForegroundColor Yellow
Get-Printer | Select-Object Name, PrinterStatus, PortName, Shared

# Step 2: Check Print Spooler
Write-Host "`n[2] Print Spooler Status:" -ForegroundColor Yellow
Get-Service -Name Spooler | Select-Object Status, StartType

# Step 3: Check print jobs
Write-Host "`n[3] Pending Print Jobs:" -ForegroundColor Yellow
Get-Printer | ForEach-Object { 
    $jobs = Get-PrintJob -PrinterName $_.Name -ErrorAction SilentlyContinue
    if ($jobs) { Write-Host "   Printer: $($_.Name) has $($jobs.Count) pending jobs" -ForegroundColor Red }
}

# Step 4: Clear print queue (uncomment to execute)
Write-Host "`n[4] To clear print queue, run these commands:" -ForegroundColor Yellow
Write-Host "   Stop-Service Spooler -Force"
Write-Host "   Remove-Item C:\Windows\System32\spool\PRINTERS\* -Recurse -Force"
Write-Host "   Start-Service Spooler"

Write-Host "`n=== Diagnostic Complete ===" -ForegroundColor Cyan""",

        "Security / BitLocker": """# ITAssist AI - BitLocker Diagnostics
# Generated by Resolution Agent

Write-Host "=== BitLocker Status Report ===" -ForegroundColor Cyan

# Step 1: BitLocker status on all drives
Write-Host "`n[1] BitLocker Status:" -ForegroundColor Yellow
Get-BitLockerVolume | Select-Object MountPoint, VolumeStatus, EncryptionMethod, KeyProtector

# Step 2: Check TPM
Write-Host "`n[2] TPM Status:" -ForegroundColor Yellow
Get-Tpm | Select-Object TpmReady, TpmEnabled, TpmActivated, TpmOwned

# Step 3: BitLocker protectors
Write-Host "`n[3] Key Protectors on C::" -ForegroundColor Yellow
(Get-BitLockerVolume -MountPoint C:).KeyProtector | Select-Object KeyProtectorId, KeyProtectorType

# Step 4: manage-bde status
Write-Host "`n[4] Detailed manage-bde status:" -ForegroundColor Yellow
manage-bde.exe -status C:

Write-Host "`n=== Diagnostic Complete ===" -ForegroundColor Cyan
Write-Host "To backup recovery key to AD: manage-bde.exe -protectors -adbackup C:" -ForegroundColor White""",

        "Backup / Storage": """# ITAssist AI - Storage & Backup Diagnostics
# Generated by Resolution Agent

Write-Host "=== Backup & Storage Diagnostic Report ===" -ForegroundColor Cyan

# Step 1: Disk space
Write-Host "`n[1] Disk Space:" -ForegroundColor Yellow
Get-Volume | Select-Object DriveLetter, FileSystemLabel, @{N='Size(GB)';E={[math]::Round($_.Size/1GB,2)}}, @{N='Free(GB)';E={[math]::Round($_.SizeRemaining/1GB,2)}}

# Step 2: Disk health
Write-Host "`n[2] Physical Disk Health:" -ForegroundColor Yellow
Get-PhysicalDisk | Select-Object FriendlyName, HealthStatus, OperationalStatus, @{N='Size(GB)';E={[math]::Round($_.Size/1GB,0)}}

# Step 3: VSS status
Write-Host "`n[3] Volume Shadow Copy Service:" -ForegroundColor Yellow
Get-Service -Name VSS | Select-Object Status, StartType
vssadmin list writers | Select-String "Writer name|State"

# Step 4: Shadow copies
Write-Host "`n[4] Shadow Copies:" -ForegroundColor Yellow
vssadmin list shadows /for=C: 2>$null | Select-String "Shadow Copy"

# Step 5: Backup event log errors
Write-Host "`n[5] Recent Backup Events:" -ForegroundColor Yellow
Get-WinEvent -LogName "Microsoft-Windows-Backup" -MaxEvents 5 -ErrorAction SilentlyContinue | 
    Select-Object TimeCreated, LevelDisplayName, Message | Format-Table -Wrap

Write-Host "`n=== Diagnostic Complete ===" -ForegroundColor Cyan""",
    }

    default_script = scripts.get(
        category,
        """# ITAssist AI - General Diagnostics
Write-Host "=== System Information ===" -ForegroundColor Cyan
Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
Write-Host "`n=== Event Log Errors (Last 10) ===" -ForegroundColor Yellow
Get-WinEvent -LogName System -MaxEvents 10 | Where-Object {$_.Level -le 2} | Select-Object TimeCreated, LevelDisplayName, Message""",
    )

    steps_map = {
        "Performance": [
            "Step 1: Run the diagnostic script to identify resource bottleneck (CPU/RAM/Disk)",
            "Step 2: If disk usage >90%, run Disk Cleanup (Win+R → cleanmgr)",
            "Step 3: Clear temp files: %temp% and C:\\Windows\\Temp",
            "Step 4: Disable startup programs via Task Manager → Startup tab",
            "Step 5: If CPU is the issue, identify the offending process and restart it",
            "Step 6: Run 'sfc /scannow' to repair corrupt system files if issue persists",
        ],
        "VPN / Remote Access": [
            "Step 1: Verify internet connectivity (ping 8.8.8.8)",
            "Step 2: Note the exact VPN error code",
            "Step 3: Flush DNS: ipconfig /flushdns",
            "Step 4: Reconnect VPN — disconnect completely and try fresh connection",
            "Step 5: If Error 720: reinstall WAN Miniport drivers via Device Manager",
            "Step 6: If Error 691: verify AD account is not locked — check with AD admin",
        ],
    }

    return {
        "resolution_steps": steps_map.get(
            category,
            [
                "Step 1: Run the generated diagnostic script",
                "Step 2: Review output for errors",
                "Step 3: Apply targeted fix based on findings",
                "Step 4: Verify issue is resolved",
                "Step 5: Document resolution in ticket",
            ],
        ),
        "script": default_script,
        "script_type": "PowerShell",
        "summary": f"Suspected {probable_cause}. Follow the steps and run the diagnostic script to confirm and resolve.",
        "estimated_time": "20-30 minutes",
        "escalation_needed": severity in ["High", "Critical"],
    }
