"""
IT Engineer Dashboard — Full ticket management with AI analysis views.
Tabs: Overview | All Tickets | Ticket Detail | Knowledge Base
"""
import streamlit as st
from ui.components import (
    render_metric_card,
    render_ticket_card,
    render_page_header,
    render_info_banner,
    render_resolution_steps,
    render_script_block,
    SEVERITY_COLORS,
    STATUS_COLORS,
    CATEGORY_ICONS,
)
from database.crud import (
    get_all_tickets,
    get_ticket_by_id,
    update_ticket_status,
    get_ticket_stats,
    get_all_knowledge_articles,
)
from agents.resolution_agent import generate_resolution
from rag.retriever import is_index_ready

@st.cache_data(show_spinner=False)
def get_cached_resolution(category: str, issue_summary: str, probable_cause: str, severity: str, sop_context: str) -> dict:
    return generate_resolution(
        category=category,
        issue_summary=issue_summary,
        probable_cause=probable_cause,
        severity=severity,
        sop_context=sop_context,
    )


def _render_full_ticket_detail_view(ticket_id: str):
    # Back button
    if st.button("← Back to Dashboard", key="back_to_dashboard_btn"):
        st.session_state.selected_ticket_id = None
        st.rerun()

    ticket = get_ticket_by_id(ticket_id)
    if not ticket:
        st.error("Ticket not found.")
        st.session_state.selected_ticket_id = None
        st.rerun()

    # Page Header
    st.markdown(
        f"""
        <div style="background:#171717; border:1px solid #2f2f2f;
             border-radius:12px; padding:20px; margin-bottom:16px;">
            <div style="font-size:18px; font-weight:700; color:#ececec; margin-bottom:8px;">
                 Ticket Detail: {ticket['ticket_id']}
            </div>
            <div style="color:#b4b4b4; font-size:13px;">
                Detailed engineering view for {ticket['username']}'s issue
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Full ticket card
    render_ticket_card(ticket, compact=False)

    # Status update
    st.markdown(
        '<div style="color:#94a3b8; font-size:13px; font-weight:600; margin:16px 0 8px;"> Update Status:</div>',
        unsafe_allow_html=True,
    )
    status_cols = st.columns(4)
    statuses = ["In Progress", "Resolved", "Escalated", "Cancelled"]
    status_icons = {"In Progress": "", "Resolved": "", "Escalated": "", "Cancelled": ""}
    for i, status in enumerate(statuses):
        with status_cols[i]:
            if st.button(
                f"{status_icons[status]} {status}",
                key=f"status_view_{ticket_id}_{status}",
                use_container_width=True,
            ):
                update_ticket_status(ticket_id, status)
                st.success(f"Ticket status updated to **{status}**")
                st.rerun()

    st.markdown("---")

    # Conversation History
    convos = ticket.get("conversations", [])
    if convos:
        with st.expander(" User Conversation History", expanded=False):
            for msg in convos:
                render_chat_message = _local_chat_msg
                render_chat_message(msg["role"], msg["message"])

    email_draft = ticket.get("resolution_notes", "")
    if email_draft and email_draft != "No email drafted":
        st.markdown(
            f"""
            <div style="background:#2f2f2f; border:1px solid #3f3f3f; border-radius:12px; padding:16px; margin:16px 0;">
                <div style="color:#ececec; font-weight:600; font-size:14px; margin-bottom:8px;"> User-Generated Email Draft (Supportive Response)</div>
                <div style="color:#ececec; font-size:13.5px; white-space:pre-wrap; background:#171717; padding:12px; border-radius:8px; border:1px solid #2f2f2f;">{email_draft}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    # AI Resolution Panel
    st.markdown(
        """
        <div style="background:#171717; border:1px solid #2f2f2f;
             border-radius:12px; padding:20px; margin:16px 0;">
            <div style="font-size:17px; font-weight:700; color:#ececec; margin-bottom:8px;">
                 AI Resolution Recommendations
            </div>
            <div style="color:#b4b4b4; font-size:13px;">
                Generated by the Resolution Agent using the ticket analysis and SOP documentation.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Generate or retrieve resolution
    res_key = f"resolution_{ticket_id}"
    if res_key not in st.session_state:
        with st.spinner(" Resolution Agent is generating recommendations..."):
            from rag.retriever import search_text
            sop_ctx = search_text(f"{ticket['category']} {ticket['issue_summary']}", k=3)

            resolution = get_cached_resolution(
                category=ticket.get("category", "Other"),
                issue_summary=ticket.get("issue_summary", ""),
                probable_cause=ticket.get("probable_cause", ""),
                severity=ticket.get("severity", "Medium"),
                sop_context=sop_ctx,
            )
            st.session_state[res_key] = resolution

    resolution = st.session_state[res_key]

    # Resolution steps
    steps = resolution.get("resolution_steps", [])
    if steps:
        st.markdown(
            '<div style="color:#94a3b8; font-size:14px; font-weight:600; margin-bottom:10px;"> Resolution Steps:</div>',
            unsafe_allow_html=True,
        )
        render_resolution_steps(steps)

    # Estimated time + escalation
    col_e, col_s = st.columns(2)
    with col_e:
        st.info(f" **Estimated Resolution Time:** {resolution.get('estimated_time', '15 mins')}")
    with col_s:
        if resolution.get("escalation_needed", False):
            st.warning(" **Escalation Recommended:** This issue requires level-2 support.")

    # Script block
    script = resolution.get("powershell_script", "")
    if script:
        st.markdown(
            '<div style="color:#94a3b8; font-size:14px; font-weight:600; margin-top:16px; margin-bottom:10px;"> Recommended Troubleshooting Script:</div>',
            unsafe_allow_html=True,
        )
        render_script_block(script, language="powershell" if "windows" in ticket.get("probable_cause", "").lower() or "win" in ticket.get("probable_cause", "").lower() else "bash")

    # Resolution notes
    st.markdown(
        '<div style="color:#94a3b8; font-size:13px; font-weight:600; margin:16px 0 6px;"> Engineer Notes:</div>',
        unsafe_allow_html=True,
    )
    notes = st.text_area(
        "Add resolution notes",
        value=ticket.get("resolution_notes", ""),
        height=100,
        placeholder="Describe what you did to resolve the issue...",
        label_visibility="collapsed",
        key=f"notes_{ticket_id}",
    )
    col_sn, col_draft = st.columns(2)
    with col_sn:
        if st.button(" Save Notes", key=f"save_notes_{ticket_id}", use_container_width=True):
            update_ticket_status(ticket_id, ticket.get("status", "In Progress"), resolution_notes=notes)
            st.success("Notes saved successfully.")
            st.rerun()
            
    with col_draft:
        if st.button(" Draft Knowledge Article", key=f"draft_kb_{ticket_id}", use_container_width=True):
            with st.spinner(" AI is drafting the Knowledge Base article..."):
                from agents.resolution_agent import draft_knowledge_article
                old_solution = "\n".join(resolution.get("resolution_steps", []))
                draft = draft_knowledge_article(
                    ticket.get("issue_summary", ""), 
                    old_solution, 
                    notes
                )
                st.session_state[f"kb_draft_{ticket_id}"] = draft
                
    if f"kb_draft_{ticket_id}" in st.session_state:
        st.markdown("---")
        st.markdown(
            '<div style="color:#a5b4fc; font-size:15px; font-weight:700; margin-bottom:8px;"> Drafted Knowledge Base Article</div>',
            unsafe_allow_html=True,
        )
        draft_content = st.session_state[f"kb_draft_{ticket_id}"]
        edited_draft = st.text_area(
            "Review and edit the drafted article before approving:",
            value=draft_content,
            height=300,
            key=f"edit_draft_{ticket_id}"
        )
        if st.button(" Approve & Save to Knowledge Base", type="primary", use_container_width=True, key=f"approve_kb_{ticket_id}"):
            from database.crud import approve_and_save_solution
            title = f"{ticket.get('category', 'General')} Issue - {ticket.get('ticket_id')}"
            approve_and_save_solution(
                ticket_id=ticket_id,
                title=title,
                category=ticket.get("category", "General"),
                content=edited_draft
            )
            st.success(" Solution approved and saved to Knowledge Base!")
            del st.session_state[f"kb_draft_{ticket_id}"]
            st.rerun()

def render_it_dashboard(username: str):
    main_col = st.columns([1])[0]
    with main_col:
        st.markdown('<div id="main-col-marker"></div>', unsafe_allow_html=True)
        if "selected_ticket_id" in st.session_state and st.session_state.selected_ticket_id:
            _render_full_ticket_detail_view(st.session_state.selected_ticket_id)
            return

        render_page_header(
            "IT Engineer Dashboard",
            f"Logged in as: {username} · All tickets with AI analysis",
        )

        tabs = st.tabs(["Overview", "All Tickets", "Knowledge Base", "Org Directory"])

        with tabs[0]:
            _render_overview()

        with tabs[1]:
            _render_all_tickets()

        with tabs[2]:
            _render_knowledge_base()

        with tabs[3]:
            _render_org_directory()


# ─────────────────────────────────────────────────────────────────────────────
# Tab 1: Overview
# ─────────────────────────────────────────────────────────────────────────────

def _render_overview():
    stats = get_ticket_stats()

    st.markdown("<br>", unsafe_allow_html=True)



    # Recent open tickets
    st.markdown(
        '<div style="color:#a5b4fc; font-size:16px; font-weight:700; margin-bottom:12px;">Recent Open Tickets</div>',
        unsafe_allow_html=True,
    )

    open_tickets = get_all_tickets(status="Open")[:5]

    if not open_tickets:
        render_info_banner(
            "No Open Tickets",
            "All tickets have been resolved or there are no tickets yet.",
            color="#22c55e",
            icon=None,
        )
    else:
        for ticket in open_tickets:
            col_left, col_right = st.columns([4, 1])
            with col_left:
                render_ticket_card(ticket, compact=True)
            with col_right:
                st.markdown("<br>", unsafe_allow_html=True)
                if st.button(
                    "View →",
                    key=f"view_ov_{ticket['ticket_id']}",
                    use_container_width=True,
                ):
                    st.session_state.selected_ticket_id = ticket["ticket_id"]
                    st.session_state.dashboard_tab = 2
                    st.rerun()

    # Category breakdown
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(
        '<div style="color:#a5b4fc; font-size:16px; font-weight:700; margin-bottom:12px;"> Tickets by Category</div>',
        unsafe_allow_html=True,
    )

    all_tickets = get_all_tickets()
    if all_tickets:
        from collections import Counter
        cat_counts = Counter(t["category"] for t in all_tickets)
        top_cats = cat_counts.most_common(5)

        for cat, count in top_cats:
            icon = CATEGORY_ICONS.get(cat, "")
            pct = count / len(all_tickets) * 100
            st.markdown(
                f"""
                <div style="margin:6px 0;">
                    <div style="display:flex; justify-content:space-between; margin-bottom:4px;">
                        <span style="color:#ececec; font-size:13px;">{icon} {cat}</span>
                        <span style="color:#10a37f; font-size:13px; font-weight:600;">{count} tickets ({pct:.0f}%)</span>
                    </div>
                    <div style="background:#171717; border-radius:4px; height:8px;">
                        <div style="background:#10a37f; width:{pct}%; height:8px; border-radius:4px;"></div>
                    </div>
                </div>
                """,
                unsafe_allow_html=True,
            )


# ─────────────────────────────────────────────────────────────────────────────
# Tab 2: All Tickets
# ─────────────────────────────────────────────────────────────────────────────

def _render_all_tickets():
    st.markdown("<br>", unsafe_allow_html=True)

    # Filters
    col1, col2, col3 = st.columns(3)
    with col1:
        status_filter = st.selectbox(
            "Filter by Status",
            ["All", "Open", "In Progress", "Resolved", "Escalated", "Cancelled"],
            key="status_filter",
        )
    with col2:
        severity_filter = st.selectbox(
            "Filter by Severity",
            ["All", "Critical", "High", "Medium", "Low"],
            key="sev_filter",
        )
    with col3:
        st.markdown("<br>", unsafe_allow_html=True)
        if st.button(" Refresh", use_container_width=True, key="refresh_tickets"):
            st.rerun()

    # Fetch and filter tickets
    status_param = None if status_filter == "All" else status_filter
    tickets = get_all_tickets(status=status_param)

    if severity_filter != "All":
        tickets = [t for t in tickets if t.get("severity") == severity_filter]

    if not tickets:
        render_info_banner("No Tickets Found", "No tickets match your filter criteria.", icon=None)
        return

    st.markdown(
        f'<div style="color:#64748b; font-size:13px; margin-bottom:12px;">Showing {len(tickets)} ticket(s)</div>',
        unsafe_allow_html=True,
    )

    for ticket in tickets:
        col_left, col_right = st.columns([5, 1])
        with col_left:
            render_ticket_card(ticket, compact=True)
        with col_right:
            st.markdown("<br>", unsafe_allow_html=True)
            if st.button("Open →", key=f"open_{ticket['ticket_id']}", use_container_width=True):
                st.session_state.selected_ticket_id = ticket["ticket_id"]
                st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# Tab 3: Ticket Detail (with Resolution Agent output)
# ─────────────────────────────────────────────────────────────────────────────

def _render_ticket_detail():
    st.markdown("<br>", unsafe_allow_html=True)

    # Ticket selector
    all_tickets = get_all_tickets()
    if not all_tickets:
        render_info_banner("No Tickets", "No tickets have been created yet.", icon=None)
        return

    ticket_options = {f"{t['ticket_id']} — {t['issue_summary'][:50]}": t["ticket_id"] for t in all_tickets}

    selected_label = st.selectbox(
        "Select Ticket:",
        list(ticket_options.keys()),
        index=0,
        key="ticket_selector",
    )
    ticket_id = ticket_options[selected_label]

    # Override from session state (clicked from other tabs)
    if "selected_ticket_id" in st.session_state and st.session_state.selected_ticket_id:
        tid = st.session_state.selected_ticket_id
        # Find matching label
        for label, tid_val in ticket_options.items():
            if tid_val == tid:
                ticket_id = tid_val
                break

    ticket = get_ticket_by_id(ticket_id)
    if not ticket:
        st.error("Ticket not found.")
        return

    # Full ticket card
    render_ticket_card(ticket, compact=False)

    # Status update
    st.markdown(
        '<div style="color:#94a3b8; font-size:13px; font-weight:600; margin:16px 0 8px;"> Update Status:</div>',
        unsafe_allow_html=True,
    )
    status_cols = st.columns(4)
    statuses = ["In Progress", "Resolved", "Escalated", "Cancelled"]
    status_icons = {"In Progress": "", "Resolved": "", "Escalated": "", "Cancelled": ""}
    for i, status in enumerate(statuses):
        with status_cols[i]:
            if st.button(
                f"{status_icons[status]} {status}",
                key=f"status_{ticket_id}_{status}",
                use_container_width=True,
            ):
                update_ticket_status(ticket_id, status)
                st.success(f"Ticket status updated to **{status}**")
                st.rerun()

    st.markdown("---")

    # Conversation History
    convos = ticket.get("conversations", [])
    if convos:
        with st.expander(" User Conversation History", expanded=False):
            for msg in convos:
                render_chat_message = _local_chat_msg
                render_chat_message(msg["role"], msg["message"])

    # User-generated email draft display (Supportive Response)
    email_draft = ticket.get("resolution_notes", "")
    if email_draft and email_draft != "No email drafted":
        st.markdown(
            """
            <div style="background:#1e293b; border:1px solid #334155; border-radius:12px; padding:16px; margin:16px 0;">
                <div style="color:#818cf8; font-weight:700; font-size:14px; margin-bottom:8px;"> User-Generated Email Draft (Supportive Response)</div>
                <div style="color:#e2e8f0; font-size:13.5px; white-space:pre-wrap; background:#0f172a; padding:12px; border-radius:8px; border:1px solid #1e293b;">""" + email_draft + """</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    # AI Resolution Panel
    st.markdown(
        """
        <div style="background:linear-gradient(135deg,#1e1b4b,#0f172a); border:1px solid #6366f1;
             border-radius:14px; padding:20px; margin:16px 0;">
            <div style="font-size:17px; font-weight:700; color:#a5b4fc; margin-bottom:8px;">
                 AI Resolution Recommendations
            </div>
            <div style="color:#64748b; font-size:13px;">
                Generated by the Resolution Agent using the ticket analysis and SOP documentation.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Generate or retrieve resolution
    res_key = f"resolution_{ticket_id}"
    if res_key not in st.session_state:
        with st.spinner(" Resolution Agent is generating recommendations..."):
            from rag.retriever import search_text
            sop_ctx = search_text(f"{ticket['category']} {ticket['issue_summary']}", k=3)

            resolution = generate_resolution(
                category=ticket.get("category", "Other"),
                issue_summary=ticket.get("issue_summary", ""),
                probable_cause=ticket.get("probable_cause", ""),
                severity=ticket.get("severity", "Medium"),
                sop_context=sop_ctx,
            )
            st.session_state[res_key] = resolution

    resolution = st.session_state[res_key]

    # Resolution steps
    steps = resolution.get("resolution_steps", [])
    if steps:
        st.markdown(
            '<div style="color:#94a3b8; font-size:14px; font-weight:600; margin-bottom:10px;"> Resolution Steps:</div>',
            unsafe_allow_html=True,
        )
        render_resolution_steps(steps)

    # Estimated time + escalation
    col_e, col_s = st.columns(2)
    with col_e:
        render_info_banner(
            "Estimated Resolution Time",
            resolution.get("estimated_time", "30 minutes"),
            color="#6366f1",
            icon=None,
        )
    with col_s:
        escalation = resolution.get("escalation_needed", False)
        render_info_banner(
            "Escalation Required",
            "Yes — escalate to senior engineer or vendor" if escalation else "No — resolvable at Tier 1/2",
            color="#ef4444" if escalation else "#22c55e",
            icon=None if escalation else "",
        )

    # PowerShell Script
    script = resolution.get("script", "")
    if script:
        st.markdown(
            '<div style="color:#94a3b8; font-size:14px; font-weight:600; margin:16px 0 8px;"> Diagnostic Script:</div>',
            unsafe_allow_html=True,
        )
        render_script_block(script, resolution.get("script_type", "PowerShell"))

    # Resolution notes
    st.markdown(
        '<div style="color:#94a3b8; font-size:13px; font-weight:600; margin:16px 0 6px;"> Engineer Notes:</div>',
        unsafe_allow_html=True,
    )
    notes = st.text_area(
        "Add resolution notes",
        value=ticket.get("resolution_notes", ""),
        height=100,
        placeholder="Describe what you did to resolve the issue...",
        label_visibility="collapsed",
        key=f"notes_{ticket_id}",
    )
    col_sn, col_draft = st.columns(2)
    with col_sn:
        if st.button(" Save Notes", key=f"save_notes_{ticket_id}", use_container_width=True):
            update_ticket_status(ticket_id, ticket.get("status", "In Progress"), resolution_notes=notes)
            st.success("Notes saved successfully.")
            st.rerun()
            
    with col_draft:
        if st.button(" Draft Knowledge Article", key=f"draft_kb_{ticket_id}", use_container_width=True):
            with st.spinner(" AI is drafting the Knowledge Base article..."):
                from agents.resolution_agent import draft_knowledge_article
                old_solution = "\n".join(resolution.get("resolution_steps", []))
                draft = draft_knowledge_article(
                    ticket.get("issue_summary", ""), 
                    old_solution, 
                    notes
                )
                st.session_state[f"kb_draft_{ticket_id}"] = draft
                
    if f"kb_draft_{ticket_id}" in st.session_state:
        st.markdown("---")
        st.markdown(
            '<div style="color:#a5b4fc; font-size:15px; font-weight:700; margin-bottom:8px;"> Drafted Knowledge Base Article</div>',
            unsafe_allow_html=True,
        )
        draft_content = st.session_state[f"kb_draft_{ticket_id}"]
        edited_draft = st.text_area(
            "Review and edit the drafted article before approving:",
            value=draft_content,
            height=300,
            key=f"edit_draft_{ticket_id}"
        )
        if st.button(" Approve & Save to Knowledge Base", type="primary", use_container_width=True, key=f"approve_kb_{ticket_id}"):
            from database.crud import approve_and_save_solution
            title = f"{ticket.get('category', 'General')} Issue - {ticket.get('ticket_id')}"
            approve_and_save_solution(
                ticket_id=ticket_id,
                title=title,
                category=ticket.get("category", "General"),
                content=edited_draft
            )
            st.success(" Solution approved and saved to Knowledge Base!")
            del st.session_state[f"kb_draft_{ticket_id}"]
            st.rerun()


def _local_chat_msg(role: str, content: str):
    """Simple inline chat message renderer for ticket detail view."""
    if role == "user":
        st.markdown(
            f'<div style="text-align:right; background:#2f2f2f; color:#ececec; border: 1px solid #3f3f3f; padding:10px 14px; border-radius:12px; margin:4px 0; font-size:13px; display:inline-block; max-width:80%; float:right; clear:both;"> {content}</div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            f'<div style="background:transparent; color:#ececec; padding:10px 0; border-radius:12px; margin:4px 0; font-size:13px; display:inline-block; max-width:85%; float:left; clear:both;"> {content}</div>',
            unsafe_allow_html=True,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Tab 4: Knowledge Base
# ─────────────────────────────────────────────────────────────────────────────

def _render_knowledge_base():
    st.markdown("<br>", unsafe_allow_html=True)

    # RAG index status
    if is_index_ready():
        render_info_banner(
            "Knowledge Base: Ready ",
            "FAISS vector index is built and ready for semantic search. "
            "Includes Microsoft Windows troubleshooting PDF + 5 SOP documents.",
            color="#22c55e",
            icon=None,
        )
    else:
        render_info_banner(
            "Knowledge Base: Not Built ",
            "Run `python rag/ingest.py` from the project root to build the FAISS index. "
            "This will process the PDF and SOP documents (~2-5 minutes).",
            color="#ef4444",
            icon=None,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # RAG Search Test
    st.markdown(
        '<div style="color:#a5b4fc; font-size:16px; font-weight:700; margin-bottom:12px;"> Test Knowledge Base Search</div>',
        unsafe_allow_html=True,
    )

    search_query = st.text_input(
        "Search knowledge base:",
        placeholder="e.g. BitLocker recovery password not working...",
        key="kb_search_input",
    )

    if st.button(" Search", key="kb_search_btn", type="primary") and search_query:
        if not is_index_ready():
            st.error("Knowledge base not built yet. Run `python rag/ingest.py` first.")
        else:
            from rag.retriever import search
            with st.spinner("Searching..."):
                results = search(search_query, k=3)

            if not results:
                st.warning("No results found.")
            else:
                for i, r in enumerate(results, 1):
                    with st.expander(f"Result {i} — {r['source']} (score: {r['score']:.3f})"):
                        st.markdown(f"```\n{r['content']}\n```")

    st.markdown("---")

    # Knowledge articles list
    st.markdown(
        '<div style="color:#a5b4fc; font-size:16px; font-weight:700; margin-bottom:12px;"> SOP Documents in Knowledge Base</div>',
        unsafe_allow_html=True,
    )

    articles = get_all_knowledge_articles()
    if not articles:
        render_info_banner("No Articles Found", "Run the app once to seed the knowledge articles.", icon=None)
    else:
        for art in articles:
            icon = CATEGORY_ICONS.get(art["category"], "")
            st.markdown(
                f"""
                <div style="background:#1e293b; border:1px solid #334155; border-radius:10px;
                     padding:14px; margin:6px 0; display:flex; justify-content:space-between; align-items:center;">
                    <div>
                        <div style="color:#e2e8f0; font-size:14px; font-weight:600;">{icon} {art['title']}</div>
                        <div style="color:#64748b; font-size:12px; margin-top:4px;">Category: {art['category']} | File: {art['filename']}</div>
                    </div>
                    <a href="{art.get('source_url', '#')}" target="_blank"
                       style="color:#6366f1; font-size:12px; text-decoration:none;"> Source</a>
                </div>
                """,
                unsafe_allow_html=True,
            )

    # PDF info
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(
        """
        <div style="background:#0f172a; border:1px solid #334155; border-radius:12px; padding:16px;">
            <div style="color:#a5b4fc; font-size:14px; font-weight:700; margin-bottom:8px;"> Microsoft PDF Knowledge Source</div>
            <div style="color:#94a3b8; font-size:13px; line-height:1.6;">
                <strong style="color:#e2e8f0;">File:</strong> troubleshoot-windows-client.pdf (68 MB)<br>
                <strong style="color:#e2e8f0;">Source:</strong> Microsoft Learn — Windows Client Troubleshooting Documentation<br>
                <strong style="color:#e2e8f0;">URL:</strong> https://learn.microsoft.com/en-us/troubleshoot/windows-client/welcome-windows-client<br>
                <strong style="color:#e2e8f0;">Content:</strong> Performance, Networking, Security, BitLocker, Printing, Backup, Identity & Access, Virtualization
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Tab 4: Org Directory Hierarchy Tree
# ─────────────────────────────────────────────────────────────────────────────

ORGANIZATION_HIERARCHY = {
    "Alexander Wright (CEO)": {
        "Sarah Jenkins (VP of Engineering)": {
            "David Vance (IT Director)": {
                "Marcus Brody (IT Lead / Manager)": [
                    "Elena Rostova (Tier-1 Support)",
                    "Thomas Miller (System Admin)"
                ],
                "Vikram Patel (Dev Lead)": [
                    "Neha Gupta (Senior Developer)",
                    "Karan Johar (Frontend Developer)"
                ]
            }
        },
        "Patricia Rose (VP of Operations)": {
            "Diana Prince (HR Manager)": [
                "Anjali Sen (HR Specialist)",
                "Rohan Das (HR Recruiter)"
            ]
        }
    }
}

def _render_org_tree(hierarchy: dict, level: int = 0, prefix: str = ""):
    items = list(hierarchy.items())
    for idx, (manager, reports) in enumerate(items):
        is_last_item = (idx == len(items) - 1)
        branch = ""
        if level > 0:
            branch = "└── " if is_last_item else "├── "
        
        icon = "" if level == 0 else "" if level == 1 else ""
        
        st.markdown(
            f"""
            <div style="font-family:monospace; color:#ececec; font-size:13.5px; display:flex; align-items:center; margin-bottom:6px; line-height:1;">
                <span style="color:#64748b; margin-right:4px; font-weight:700; white-space:pre;">{prefix}{branch}</span>
                <span style="margin-right:6px;">{icon}</span>
                <span style="background:#1e293b; border:1px solid #334155; border-radius:6px; padding:4px 8px; font-weight:600;">{manager}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )
        
        next_prefix = prefix + ("    " if is_last_item else "│   ") if level > 0 else (prefix + "    " if is_last_item else prefix + "│   ")
        if isinstance(reports, dict):
            _render_org_tree(reports, level + 1, next_prefix)
        elif isinstance(reports, list):
            for e_idx, emp in enumerate(reports):
                is_last_emp = (e_idx == len(reports) - 1)
                emp_branch = "└── " if is_last_emp else "├── "
                st.markdown(
                    f"""
                    <div style="font-family:monospace; color:#94a3b8; font-size:13px; display:flex; align-items:center; margin-bottom:4px; line-height:1;">
                        <span style="color:#64748b; margin-right:4px; font-weight:700; white-space:pre;">{next_prefix}{emp_branch}</span>
                        <span style="margin-right:6px;"></span>
                        <span style="background:#0f172a; border:1px solid #1e293b; border-radius:6px; padding:3px 6px;">{emp}</span>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

def _render_org_directory():
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(
        """
        <div style="background:#171717; border:1px solid #2f2f2f; border-radius:12px; padding:20px; margin-bottom:16px;">
            <div style="font-size:18px; font-weight:700; color:#ececec; margin-bottom:8px;">
                 Organization Directory & Manager Hierarchy Tree
            </div>
            <div style="color:#b4b4b4; font-size:13px;">
                Visual mapping of corporate hierarchy and reporting relationships in a structural tree format.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    
    with st.container():
        _render_org_tree(ORGANIZATION_HIERARCHY)
